# for standing up a single node instance of zookeeper. 
# overrides default image volume exposure to be more inclusive. 
#
FROM jplock/zookeeper
MAINTAINER David Holiday <dholiday@moesol.com>

VOLUME ["/opt/zookeeper"]

